:build:
  :scheme: "Last Time"
  :app: true
  :ios: true
  :project: "Last Time.xcodeproj"
  
:code_signing:
  :ios_dist: "iPhone Distribution: James Moore"
  :ios_release: "iPhone Distribution: James Moore"
  :ios_debug: "iPhone Developer: James Moore (HGZS2NAYVG)"
  :keychain_file: "~/Library/Keychains/james.keychain"
  
:testflight:
  :api_token: "a3e60f758620c870b4c0db40b87b1034_MjYwNTMwMjAxMS0xMi0yNyAxNjozMTowOC4wNTcyNjQ"
  :team_token: "7dc090a5932acba7bcf3c281394f4a6a_NTAwNTgyMDExLTEyLTI3IDE2OjM1OjAyLjE4Mzg5MA"
