:build:
  :scheme: "Last Time"
  :app: true
  :ios: true
  :project: "Last Time.xcodeproj"
  
:code_signing:
  :ios_dist: "iPhone Distribution: James Moore"
  :ios_release: "iPhone Distribution: James Moore"
  :ios_debug: "iPhone Developer: James Moore (HGZS2NAYVG)"
  :keychain_file: "~/Library/Keychains/james.keychain"
  
:verification:
  :keychain_group: "3C6XYXB3FQ.me.jmoore.LastTime"
  :archs: ["armv7", "arm64"]